[33macd5b0c[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmaster[m[33m, [m[1;31morigin/master[m[33m)[m Split rule scoring into structural vs lexical tiers, fixing the formality confound found earlier: analyze_confound.py showed r=0.722 correlation between flag density and sentence length on human text, and every flag in that correlation came from lexical (word-list) rules. Structural rules (rule_of_three_outline, em_dash_density, etc.) never fired on human text, so they weren't part of the problem -- but aren't proven clean either, just untested. AnalysisResult, app.py, and analyze_confound.py now report structural and lexical signal separately instead of one blended number. 69 tests passing.
[33m9ce15d9[m Add LAYER2_FINDINGS.md: first real Binoculars run on Colab T4. Direction correct but fragile -- one outlier document accounts for 80% of the apparent human/AI gap. Also surfaces a concerning finding: Layer 2's per-document ranking on human text closely tracks Layer 1's flag count, suggesting both may be measuring formal register rather than authorship independently.
[33m4e3168f[m Make document-level flags (em_dash_density, boldface_overuse) exclusion-aware: mask excluded-span characters before computing rates, so legal citations can't trip a rate flag purely from characters already excluded at the span level. Widens the statute-citation regex to allow em dashes in act titles. 55 tests passing, closes a known v1 limitation.
[33mb276c72[m Rewrite README.md — the old one described an 8-rule, 11-test proof of concept and never mentioned the exclusion filter, Streamlit UI, measurement scripts, or FINDINGS.md.
[33ma41b12c[m Sync TODO.md's FPR section with FINDINGS.md — was still saying 'real number still missing' after the comparison was already done and documented.
[33maae4f75[m Added compare_corpora.py script -51 tests and FINDINGS.md with real measured human-vs-AI results. Also commits the earlier .gitignore update excluding corpus/ and ai_corpus/ from version control.
[33me91dcd7[m Show legal-boilerplate exclusion in the Streamlit UI: gray-highlighted excluded spans, 'Suppressed (legal)' metric. 49 tests passing (fixes a dropped test_empty_input_shows_warning from an earlier full-file edit).
[33maf0e7eb[m Added FPR measurement script and legal boilerplate exclusion filter (48 tests). Removed curly_quotes from scoring based on real evidence, it produced 87.5% of flags on a genuine human-written Word document, caused by Word's default quote autocorrect, not authorship signal.
[33m124adcc[m Added legal boilerplate exclusion filter, statutory case citations and standard contract phrases are detected and suppress overlapping Layer 1 flags. 45 tests passing.
[33md754cdd[m Added 4 patterns, notability emphasis, outline-style headings, copula avoidance, inline-header lists, 22 of 24 official patterns now implemented, 36 tests passing. Fixes a regex bug in inline_header_list caught by its own test (colon belongs inside ** not after).
[33m6bcb5b2[m Adding 4 patterns significance inflation, superficial -ing analysis, boldface overuse, generic positive conclusions, 18 of 24 official patterns now implemented, 31 tests passing. Also fixes an indentation bug in scorer.py introduced during manual editing.
[33md833bdd[m Added 4 patterns emoji, vague attribution, sycophantic tone, knowledge-cutoff disclaimer, 14 of 24 official patterns now implemented, 26 tests passing
[33m5a31846[m Added 4 patterns promotional language, AI vocabulary, false ranges, curly quotes, 10 of 24 official patterns now implemented, 21 tests passing
[33me31e929[m Add regression test for smart-quote and markdown-emphasis bug
[33md4ad28c[m Add Streamlit shell (app.py); fix smart-quote and markdown-emphasis regressions in negative_parallelism and rule_of_three_outline
[33me778134[m Layer 1: 6 of 24 patterns implemented, 11 tests passing, gap tracked in TODO.md
